spring:
  application:
    name: zuul-edge-server
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 9090

zuul:
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 10000
  
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: false
