spring:
  application:
    name: employee-payroll
  datasource:    hikari:      jdbc-url: jdbc:h2:file:D:/Other/employeepayroll
      driver-class-name: org.h2.Driver
      username: sa
      password: manage
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true

server:  port: 8300
  
employee-service:
  ribbon:
    listOfServers: http://localhost:8100, http://localhost:8101
    
role-service:
  ribbon:
    listOfServers: http://localhost:8200, http://localhost:8201
