spring:
  application:
    name: employee-payroll
  datasource:    hikari:      jdbc-url: jdbc:h2:file:~/employeepayroll;AUTO_SERVER=true
      driver-class-name: org.h2.Driver
      username: sa
      password: manage
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
  main:    allow-bean-definition-overriding: true      zipkin:    base-url: http://localhost:9411/

server:  port: 8300
  
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: false