spring:
  application:
    name: employee-service  datasource:    hikari:      jdbc-url: jdbc:h2:file:~/employeedb;AUTO_SERVER=true
      driver-class-name: org.h2.Driver
      username: sa
      password: manage  h2:    console:      path: /h2-console
      enabled: true
  jpa:    hibernate:      ddl-auto: none
  flyway:    baseline-on-migrate: true
    
eureka:  client:    service-url: 
      defaultZone: http://localhost:8761/eureka/
    healthcheck:      enabled: false
    
    
server:  port: 8100
  