spring:
  application:
    name: employee-service  datasource:    hikari:      jdbc-url: jdbc:h2:file:D:/Other/employeedb
      driver-class-name: org.h2.Driver
      username: sa
      password: manage  h2:    console:      path: /h2-console
      enabled: true
  jpa:    hibernate:      ddl-auto: none
  flyway:    baseline-on-migrate: true
    
    
server:  port: 8100
  