spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: /Users/preetiverma/Documents/git/springcloudrepo
            
server:
  port: 8888