DROP TABLE IF EXISTS EMPLOYEE_PAYROLL;
CREATE TABLE IF NOT EXISTS EMPLOYEE_PAYROLL (
	PAYROLL_ID INT AUTO_INCREMENT,
	EMP_ID INT, 
	FIRST_NAME VARCHAR(255), 
	LAST_NAME VARCHAR(255), 
	ROLE_DESC VARCHAR(255),
	ROLE_ID INT,
	ROLE_NAME VARCHAR(255)
);